-- Product change logs schema for kasher_logs database

CREATE TABLE IF NOT EXISTS `product_change_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `sub_user_id` INT DEFAULT NULL,
  `event_type` VARCHAR(100) NOT NULL,
  `entity_type` VARCHAR(100) NOT NULL,
  `entity_id` BIGINT DEFAULT NULL,
  `product_id` INT DEFAULT NULL,
  `before_state_json` JSON DEFAULT NULL,
  `after_state_json` JSON DEFAULT NULL,
  `delta_json` JSON DEFAULT NULL,
  `source_module` VARCHAR(255) DEFAULT NULL,
  `source_reference` VARCHAR(255) DEFAULT NULL,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `user_agent` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pcl_user_id` (`user_id`),
  KEY `idx_pcl_sub_user_id` (`sub_user_id`),
  KEY `idx_pcl_product_id` (`product_id`),
  KEY `idx_pcl_event_type` (`event_type`),
  KEY `idx_pcl_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `customer_change_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `sub_user_id` INT DEFAULT NULL,
  `event_type` VARCHAR(100) NOT NULL,
  `entity_type` VARCHAR(100) NOT NULL,
  `entity_id` BIGINT DEFAULT NULL,
  `customer_id` INT DEFAULT NULL,
  `sale_id` INT DEFAULT NULL,
  `debt_id` INT DEFAULT NULL,
  `currency` VARCHAR(10) DEFAULT NULL,
  `before_state_json` JSON DEFAULT NULL,
  `after_state_json` JSON DEFAULT NULL,
  `delta_json` JSON DEFAULT NULL,
  `source_module` VARCHAR(255) DEFAULT NULL,
  `source_reference` VARCHAR(255) DEFAULT NULL,
  `ip_address` VARCHAR(45) DEFAULT NULL,
  `user_agent` VARCHAR(255) DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_ccl_user_id` (`user_id`),
  KEY `idx_ccl_sub_user_id` (`sub_user_id`),
  KEY `idx_ccl_customer_id` (`customer_id`),
  KEY `idx_ccl_sale_id` (`sale_id`),
  KEY `idx_ccl_debt_id` (`debt_id`),
  KEY `idx_ccl_event_type` (`event_type`),
  KEY `idx_ccl_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
